from PySide6.QtGui import QFont
FONT_FAMILY = "Arial"
DEFAULT_POINT_SIZE = 11
DEFAULT = QFont(FONT_FAMILY, pointSize=DEFAULT_POINT_SIZE)
DEFAULT_LARGE = QFont(FONT_FAMILY, pointSize=DEFAULT_POINT_SIZE+5)